import GRDB

/// A typed column generated by `@Table`.
public struct TableColumn<Value: Sendable>: Sendable {
    public let name: String

    public init(_ name: String) {
        self.name = name
    }

    public var asc: TableOrder { TableOrder(GRDB.Column(name).asc) }
    public var desc: TableOrder { TableOrder(GRDB.Column(name).desc) }
}

public struct TablePredicate: Sendable {
    let expression: SQLExpression

    public static func && (lhs: Self, rhs: Self) -> Self {
        Self(expression: lhs.expression && rhs.expression)
    }

    public static func || (lhs: Self, rhs: Self) -> Self {
        Self(expression: lhs.expression || rhs.expression)
    }
}

public struct TableOrder: Sendable {
    let ordering: SQLOrdering

    init(_ ordering: SQLOrdering) {
        self.ordering = ordering
    }
}

public func == <Value: DatabaseValueConvertible & Sendable>(lhs: TableColumn<Value>, rhs: Value) -> TablePredicate {
    TablePredicate(expression: GRDB.Column(lhs.name) == rhs)
}

public func != <Value: DatabaseValueConvertible & Sendable>(lhs: TableColumn<Value>, rhs: Value) -> TablePredicate {
    TablePredicate(expression: GRDB.Column(lhs.name) != rhs)
}

public func < <Value: DatabaseValueConvertible & Comparable & Sendable>(lhs: TableColumn<Value>, rhs: Value) -> TablePredicate {
    TablePredicate(expression: GRDB.Column(lhs.name) < rhs)
}

public func > <Value: DatabaseValueConvertible & Comparable & Sendable>(lhs: TableColumn<Value>, rhs: Value) -> TablePredicate {
    TablePredicate(expression: GRDB.Column(lhs.name) > rhs)
}

public func == <Value: DatabaseValueConvertible & Sendable>(lhs: TableColumn<Value?>, rhs: Value?) -> TablePredicate {
    TablePredicate(expression: GRDB.Column(lhs.name) == rhs)
}

public func != <Value: DatabaseValueConvertible & Sendable>(lhs: TableColumn<Value?>, rhs: Value?) -> TablePredicate {
    TablePredicate(expression: GRDB.Column(lhs.name) != rhs)
}

public struct TableQuery<Record: TableModel>: Sendable {
    let pool: DatabasePool
    let predicate: TablePredicate?
    let ordering: TableOrder?
    let limitCount: Int?

    init(pool: DatabasePool, predicate: TablePredicate? = nil, ordering: TableOrder? = nil, limitCount: Int? = nil) {
        self.pool = pool
        self.predicate = predicate
        self.ordering = ordering
        self.limitCount = limitCount
    }

    public func `where`(_ makePredicate: (Record.Columns) -> TablePredicate) -> Self {
        let next = makePredicate(Record.columns)
        let combined = predicate.map { $0 && next } ?? next
        return Self(pool: pool, predicate: combined, ordering: ordering, limitCount: limitCount)
    }

    public func order(_ makeOrder: (Record.Columns) -> TableOrder) -> Self {
        Self(pool: pool, predicate: predicate, ordering: makeOrder(Record.columns), limitCount: limitCount)
    }

    public func limit(_ count: Int) -> Self {
        Self(pool: pool, predicate: predicate, ordering: ordering, limitCount: max(0, count))
    }

    public func fetchAll() async throws -> [Record] {
        let predicate = self.predicate
        let ordering = self.ordering
        let limitCount = self.limitCount
        return try await pool.read { db in
            try Self.request(predicate: predicate, ordering: ordering, limitCount: limitCount).fetchAll(db)
        }
    }

    public func fetchOne() async throws -> Record? {
        let predicate = self.predicate
        let ordering = self.ordering
        return try await pool.read { db in
            try Self.request(predicate: predicate, ordering: ordering, limitCount: 1).fetchOne(db)
        }
    }

    public func observe() -> TableObservation<Record> {
        let predicate = self.predicate
        let ordering = self.ordering
        let limitCount = self.limitCount
        let observation = ValueObservation.tracking { db in
            try Self.request(predicate: predicate, ordering: ordering, limitCount: limitCount).fetchAll(db)
        }
        return TableObservation(observation.values(in: pool, bufferingPolicy: .bufferingNewest(1)))
    }

    private static func request(
        predicate: TablePredicate?, ordering: TableOrder?, limitCount: Int?
    ) -> QueryInterfaceRequest<Record> {
        var request = Record.all()
        if let predicate { request = request.filter(predicate.expression) }
        if let ordering { request = request.order(ordering.ordering) }
        if let limitCount { request = request.limit(limitCount) }
        return request
    }
}

/// A cancellable asynchronous stream of query snapshots.
public struct TableObservation<Record: TableModel>: AsyncSequence, Sendable {
    public typealias Element = [Record]

    private let base: AsyncValueObservation<[Record]>

    init(_ base: AsyncValueObservation<[Record]>) {
        self.base = base
    }

    public func makeAsyncIterator() -> Iterator {
        Iterator(base.makeAsyncIterator())
    }

    public struct Iterator: AsyncIteratorProtocol {
        private var base: AsyncValueObservation<[Record]>.Iterator

        init(_ base: AsyncValueObservation<[Record]>.Iterator) {
            self.base = base
        }

        public mutating func next() async throws -> [Record]? {
            try await base.next()
        }
    }
}
