platform :ios, '15.0'
install! 'cocoapods', :integrate_targets => false

target 'ORMKitPodExample' do
  pod 'GRDB.swift', :git => 'https://github.com/groue/GRDB.swift.git', :tag => 'v7.11.1'
  pod 'ORMKit', :path => '../..'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
